### PR TITLE
Fix: first file upload for a issuer results in blank file uploaded to minio

### PR DESCRIPTION
**Pull request by varadeth**
@tejash-jl @dileepbapat please review
Fixes [https://github.com/Sunbird-RC/community/issues/258](https://github.com/Sunbird-RC/community/issues/258)

### CODE REVIEW

**Comment by tejash-jl** [comment]
@varadeth do we need that recursive call if the bucket doesn't exist?

**Comment by varadeth** [comment]
> @varadeth do we need that recursive call if the bucket doesn't exist?

yes I think, if there is delay in getting that bucket created due to some issues. It is better that we have a recursive call

**Comment by tejash-jl** [comment]
@varadeth i think the bucket creation need not be checked for every call, it can be done one time.
I have modified the same here 
https://github.com/Sunbird-RC/sunbird-rc-core/pull/150

**Comment by dileepbapat** [comment]
already handled in other PR

**Pull request closed without merging**
